---
apiVersion: v1
kind: Namespace
metadata:
  name: nginx-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-app
  namespace: nginx-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      nodeSelector:
          role: intel
      containers:
        - name: nginx
          image: public.ecr.aws/nginx/nginx:1.21
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - name: tcp
              containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: nginx-app
spec:
  ports:
  - name: http
    port: 80
    targetPort: 80
  selector:
    app: nginx
  type: NodePort
---
#
#
# With host on loadbalancer Listener rule
# you can put on same LB rule to diferent services, this is a example
#
#
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: nginx-app
  name: ingress-host-nginx
  annotations:
    # https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.2/guide/ingress/annotations/
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/load-balancer-name: empresa-env-alb-external
    alb.ingress.kubernetes.io/group.name: empresa-env-alb-external
    alb.ingress.kubernetes.io/group.order: '2'
    alb.ingress.kubernetes.io/security-groups: sg-xxxxxxxxxx
    alb.ingress.kubernetes.io/actions.redirect: "{\"Type\": \"redirect\", \"RedirectConfig\": {\"Protocol\": \"HTTPS\", \"Port\": \"443\", \"StatusCode\": \"HTTP_301\"}}"
    alb.ingress.kubernetes.io/listen-ports: "[{\"HTTP\":80,\"HTTPS\": 443}]"
    alb.ingress.kubernetes.io/load-balancer-attributes: "idle_timeout.timeout_seconds=360"
    alb.ingress.kubernetes.io/certificate-arn: "arn:aws:acm:us-east-1:xxxxxxxx:certificate/xxxxxx-xxxx-xxxx-xxxx-xxxxxxx"
    # alb.ingress.kubernetes.io/ip-address-type: dualstack
    alb.ingress.kubernetes.io/backend-protocol: http
    alb.ingress.kubernetes.io/healthcheck-path: /health-check
spec:
  ingressClassName: alb
  rules:
    - host: nginx.labs.clouddog.com.br # Line add to use host
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: nginx-service
              port:
                number: 80

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: nginx-app-hpa
spec:
  maxReplicas: 35
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nginx-app
  targetCPUUtilizationPercentage: 75
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: nginx-app-pdb
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: nginx-app