# Example to use the RBAC/Role with ServiceAccount
# Create the service-configuratinon, like the service-configuration/example
# Use the same ServiceAccountName
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: serviceaccount-dev
  namespace: dev
  annotations:
     eks.amazonaws.com/role-arn: "arn:aws:iam::9999999:role/role-arn-here"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-app2
  namespace: nginx-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx2
  template:
    metadata:
      labels:
        app: nginx2
    spec:
    
      ## Service Account Name Here
      serviceAccountName: serviceaccount-dev
      ##

      containers:
        - name: nginx2
          image: public.ecr.aws/nginx/nginx:1.21
          ports:
            - name: tcp
              containerPort: 80