server:
  global:
    scrape_interval: 30s
    evaluation_interval: 30s
    # podAnnotations:
    #   karpenter.sh/do-not-evict: "true"
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 500m
      memory: 512Mi
  # remoteWrite:
  #   -
  #     queue_config:
  #       max_samples_per_send: 1000
  #       max_shards: 200
  #       capacity: 2500

  # Use a statefulset instead of a deployment for resiliency
  #
  statefulSet:
    enabled: true

  nodeSelector:
    role: monitoring

  persistentVolume:
    storageClass: gp3
    size: 20Gi


prometheus-node-exporter:
  enabled: false

kube-state-metrics:
  enabled: true

# extraScrapeConfigs: |
#   - job_name: 'kubernetes-nodes'
#     kubernetes_sd_configs:
#       - role: node
#     relabel_configs:
#       - source_labels: [__meta_kubernetes_node_name]
#         action: replace
#         target_label: node


